version: '3'

services:
  psdbmysql:
    image: rhel7-percona-server:8.0.13
    volumes:
      - /srv/docker-data/psdbmysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd#1"
    ports:
     - 3306:3306
    networks:
      ipaddr:
        ipv4_address: 172.17.0.2
networks:
  ipaddr:
    external:
      name: docker1
